Repository zauberzeug/lizard, pull requests merged in 2024-11, with the labels that each got.

#84 Add speed tracking to Odrive
  docs/module_reference.md
Labels: documentation

#89 Buffer comparison cast fix
  main/modules/serial.cpp
Labels: bug

#85 Expander improvements II
  main/modules/core.cpp
  main/modules/expander.cpp
  main/modules/expander.h
  main/modules/proxy.cpp
Labels: enhancement

#74 Expander improvements I
  docs/module_reference.md
  main/main.cpp
  main/modules/expander.cpp
  main/modules/expander.h
  main/modules/proxy.cpp
  main/modules/serial.cpp
  main/modules/serial.h
Labels: enhancement

#93 update: tuned default timing
  configure.py
  main/main.cpp
  main/modules/expander.cpp
Labels: bug

#94 Imu fix
  main/modules/BNO055ESP32.cpp
  main/modules/imu.cpp
Labels: bug

#95 Check relevant pins for p0.flash()
  docs/module_reference.md
  main/modules/expander.cpp
  main/modules/expander.h
Labels: bug

#98 Expander watchdog for documentation
  docs/machine_safety.md
Labels: documentation

#104 Proxy defaults with static functions
  main/modules/analog.cpp
  main/modules/analog.h
  main/modules/can.cpp
  main/modules/can.h
  main/modules/canopen_master.cpp
  main/modules/canopen_master.h
  main/modules/canopen_motor.cpp
  main/modules/canopen_motor.h
  main/modules/d1_motor.cpp
  main/modules/d1_motor.h
  main/modules/dunker_motor.cpp
  main/modules/dunker_motor.h
  main/modules/dunker_wheels.cpp
  main/modules/dunker_wheels.h
  main/modules/expander.cpp
  main/modules/expander.h
  main/modules/imu.cpp
  main/modules/imu.h
  main/modules/input.cpp
  main/modules/input.h
  main/modules/linear_motor.cpp
  main/modules/linear_motor.h
  main/modules/mcp23017.cpp
  main/modules/mcp23017.h
  main/modules/module.cpp
  main/modules/module.h
  main/modules/odrive_motor.cpp
  main/modules/odrive_motor.h
  main/modules/odrive_wheels.cpp
  main/modules/odrive_wheels.h
  main/modules/output.cpp
  main/modules/output.h
  main/modules/proxy.cpp
  main/modules/pwm_output.cpp
  main/modules/pwm_output.h
  main/modules/rmd_motor.cpp
  main/modules/rmd_motor.h
  main/modules/rmd_pair.cpp
  main/modules/rmd_pair.h
  main/modules/roboclaw.cpp
  main/modules/roboclaw.h
  main/modules/roboclaw_motor.cpp
  main/modules/roboclaw_motor.h
  main/modules/roboclaw_wheels.cpp
  main/modules/roboclaw_wheels.h
  main/modules/stepper_motor.cpp
  main/modules/stepper_motor.h
Labels: bug, enhancement

#103 Introduce pre-commit hooks
  .github/zip_content.txt
  .gitignore
  .pre-commit-config.yaml
  .syncignore
  backtrace.sh
  examples/ota_example/main.py
  examples/ros/docker.sh
  main/.gitignore
  main/compilation/action.h
  main/compilation/await_condition.cpp
  main/compilation/await_condition.h
  main/compilation/await_routine.cpp
  main/compilation/await_routine.h
  main/compilation/method_call.cpp
  main/compilation/method_call.h
  main/compilation/property_assignment.cpp
  main/compilation/property_assignment.h
  main/compilation/routine.h
  main/compilation/routine_call.cpp
  main/compilation/routine_call.h
  main/compilation/rule.h
  main/compilation/variable_assignment.cpp
  main/compilation/variable_assignment.h
  main/component.mk
  main/modules/BNO055ESP32.cpp
  main/modules/BNO055ESP32.h
  main/modules/core.cpp
  main/modules/core.h
  main/modules/d1_motor.h
  main/modules/dunker_motor.cpp
  main/modules/input.h
  main/modules/linear_motor.h
  main/modules/odrive_motor.h
  main/modules/output.h
  main/modules/proxy.h
  main/modules/rmd_motor.h
  main/modules/roboclaw.h
  main/parser.h
  main/storage.h
  main/utils/string_utils.cpp
  main/utils/string_utils.h
  main/utils/timing.cpp
  main/utils/timing.h
Labels: enhancement

#107 Owl Hotfixes and proxy defaults fix
  gen_parser.sh
  main/modules/bluetooth.cpp
  main/modules/bluetooth.h
  main/modules/module.cpp
  main/modules/motor_axis.cpp
  main/modules/motor_axis.h
  main/modules/serial.cpp
  main/modules/serial.h
  main/parser.h
Labels: bug
